version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  user_service:
    build: .
    container_name: user_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - user_service_db
      - kafka
    environment:
      DATASOURCE_URL: jdbc:postgresql://user_service_db:5432/user_service
      DATASOURCE_USERNAME: evgenia
      DATASOURCE_PASSWORD: aston24
      KAFKA_SERVER: kafka:9092
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  user_service_db:
    image: postgres:15
    container_name: user_service_db
    environment:
      POSTGRES_USER: evgenia
      POSTGRES_PASSWORD: aston24
      POSTGRES_DB: user_service
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U evgenia -d user_service" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pgdata: