version: '3.8'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: db
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: